/* Surgical completion of Ch 15 — fills VA-04 to VA-10 SVGs, NODES, MCQs,
   adds more DTs and subjective Qs. Run: node scripts/complete-ch15.js */
const fs = require('fs');
const path = require('path');
const DATA = path.resolve(__dirname, '../02_chapters/violent-asphyxia/data.js');
let data = fs.readFileSync(DATA, 'utf8');

const SVGS = {

VA04: `<svg viewBox="0 0 1600 1000" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">Ligature Mark in Hanging — 7 Features</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">The single most-tested external finding · differentiates hanging from strangulation</text>

<g data-node-id="lm-direction"><rect class="body-white" x="60" y="120" width="490" height="200" rx="14"/><path d="M 74,120 H 536 A 14,14 0 0 1 550,134 V 180 H 60 V 134 A 14,14 0 0 1 74,120 Z" fill="url(#gBlue)"/><text x="80" y="160" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">1️⃣ DIRECTION</text><text x="80" y="220" class="t-keylbl">Hanging:</text><text x="180" y="220" class="t-keyval"><strong>OBLIQUE</strong> — rises toward knot</text><text x="80" y="250" class="t-keylbl">Strangulation:</text><text x="230" y="250" class="t-keyval">HORIZONTAL</text><text x="80" y="288" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Most reliable single distinguishing feature</text><circle class="ic" cx="520" cy="138" r="12"/><text class="t-info" x="520" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-continuity"><rect class="body-white" x="570" y="120" width="490" height="200" rx="14"/><path d="M 584,120 H 1046 A 14,14 0 0 1 1060,134 V 180 H 570 V 134 A 14,14 0 0 1 584,120 Z" fill="url(#gGreen)"/><text x="590" y="160" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">2️⃣ CONTINUITY</text><text x="590" y="220" class="t-keylbl">Hanging:</text><text x="690" y="220" class="t-keyval"><strong>INCOMPLETE</strong> — broken at knot</text><text x="590" y="250" class="t-keylbl">Strangulation:</text><text x="740" y="250" class="t-keyval">COMPLETE (fully encircles neck)</text><text x="590" y="288" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Ligature lifts off skin at knot in hanging</text><circle class="ic" cx="1040" cy="138" r="12"/><text class="t-info" x="1040" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-level"><rect class="body-white" x="1080" y="120" width="460" height="200" rx="14"/><path d="M 1094,120 H 1526 A 14,14 0 0 1 1540,134 V 180 H 1080 V 134 A 14,14 0 0 1 1094,120 Z" fill="url(#gOrange)"/><text x="1100" y="160" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">3️⃣ LEVEL vs THYROID</text><text x="1100" y="220" class="t-keylbl">Hanging:</text><text x="1200" y="220" class="t-keyval"><strong>ABOVE</strong> thyroid (near chin)</text><text x="1100" y="250" class="t-keylbl">Strangulation:</text><text x="1250" y="250" class="t-keyval">AT or BELOW thyroid</text><text x="1100" y="288" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Thyroid cartilage = anatomical landmark</text><circle class="ic" cx="1510" cy="138" r="12"/><text class="t-info" x="1510" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-texture"><rect class="body-white" x="60" y="340" width="490" height="200" rx="14"/><path d="M 74,340 H 536 A 14,14 0 0 1 550,354 V 400 H 60 V 354 A 14,14 0 0 1 74,340 Z" fill="url(#gPurple)"/><text x="80" y="380" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">4️⃣ TEXTURE / PATTERN</text><text x="80" y="440" class="t-keyval">Reproduces ligature surface — rope twist,</text><text x="80" y="464" class="t-keyval">leather stitching, dupatta weave, cable ridges.</text><text x="80" y="494" class="t-keylbl">Hard ligature:</text><text x="220" y="494" class="t-keyval">Sharp, deep, parchment-like</text><text x="80" y="518" class="t-keylbl">Soft ligature:</text><text x="220" y="518" class="t-keyval">Shallow, broad, often subtle</text><circle class="ic" cx="520" cy="358" r="12"/><text class="t-info" x="520" y="364" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-colour"><rect class="body-white" x="570" y="340" width="490" height="200" rx="14"/><path d="M 584,340 H 1046 A 14,14 0 0 1 1060,354 V 400 H 570 V 354 A 14,14 0 0 1 584,340 Z" fill="url(#gRed)"/><text x="590" y="380" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">5️⃣ COLOUR</text><text x="590" y="440" class="t-keylbl">Initial:</text><text x="690" y="440" class="t-keyval">Pale / yellow-brown</text><text x="590" y="470" class="t-keylbl">After hours:</text><text x="730" y="470" class="t-keyval">Dark brown, parchment-like</text><text x="590" y="500" class="t-keylbl">Mechanism:</text><text x="730" y="500" class="t-keyval">Drying + shrinkage of compressed dermis</text><text x="590" y="528" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Parchmentisation = a key sign of vital reaction</text><circle class="ic" cx="1040" cy="358" r="12"/><text class="t-info" x="1040" y="364" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-knot"><rect class="body-white" x="1080" y="340" width="460" height="200" rx="14"/><path d="M 1094,340 H 1526 A 14,14 0 0 1 1540,354 V 400 H 1080 V 354 A 14,14 0 0 1 1094,340 Z" fill="url(#gGrey)"/><text x="1100" y="380" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">6️⃣ KNOT IMPRESSION</text><text x="1100" y="440" class="t-keyval">Distinct pressure mark at knot site.</text><text x="1100" y="470" class="t-keyval">Helps identify ligature type + technique.</text><text x="1100" y="510" class="t-keylbl">Typical:</text><text x="1190" y="510" class="t-keyval">Posterior (occipital)</text><text x="1100" y="538" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Atypical knots → side / front</text><circle class="ic" cx="1510" cy="358" r="12"/><text class="t-info" x="1510" y="364" text-anchor="middle">ⓘ</text></g>

<g data-node-id="lm-vital"><rect class="body-white" x="60" y="560" width="1480" height="240" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 74,560 H 1526 A 14,14 0 0 1 1540,574 V 620 H 60 V 574 A 14,14 0 0 1 74,560 Z" fill="url(#gBlue)"/><text x="800" y="600" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white" text-anchor="middle">7️⃣ VITAL REACTION ★ (= antemortem marker)</text><text x="100" y="660" class="t-keylbl">Antemortem signs around the mark:</text><text x="120" y="688" class="t-keyval">• Bruising (ecchymosis) — small haemorrhages in skin / subcutaneous tissue</text><text x="120" y="712" class="t-keyval">• Abrasions — friction marks on edges</text><text x="120" y="736" class="t-keyval">• Oedema / inflammation</text><text x="120" y="760" class="t-keyval">• Sternomastoid muscle haemorrhage on dissection</text><text x="120" y="784" class="t-keyval">• <strong>Salivary dribbling</strong> from corner of mouth opposite knot (★ NEET-PG 2016)</text><circle class="ic" cx="1510" cy="578" r="14"/><text class="t-info" x="1510" y="584" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="820" width="1480" height="60" rx="10" fill="url(#gOrange)"/><text x="800" y="858" font-family="Inter,system-ui,sans-serif" font-size="15" font-weight="700" fill="white" text-anchor="middle">🎯 Memory: "DCLT-CKV" — Direction · Continuity · Level · Texture · Colour · Knot · Vital</text>

<rect x="60" y="900" width="1480" height="60" rx="10" fill="url(#gGreen)"/><text x="800" y="938" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">⭐ Hanging: OBLIQUE + INCOMPLETE + ABOVE thyroid · Strangulation: HORIZONTAL + COMPLETE + AT/BELOW</text>
</svg>`,

VA05: `<svg viewBox="0 0 1600 1100" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">Strangulation — 6 Subtypes</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">Constriction of neck by external force (NOT body weight) · mostly HOMICIDAL</text>

<g data-node-id="str-ligature"><rect class="body-white" x="60" y="120" width="490" height="290" rx="14"/><path d="M 74,120 H 536 A 14,14 0 0 1 550,134 V 195 H 60 V 134 A 14,14 0 0 1 74,120 Z" fill="url(#gRed)"/><text x="80" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🪢 1. Ligature Strangulation</text><text x="80" y="240" class="t-keylbl">Agent:</text><text x="160" y="240" class="t-keyval">Rope, scarf, dupatta, wire, electrical cable</text><text x="80" y="272" class="t-keylbl">Mark:</text><text x="160" y="272" class="t-keyval">HORIZONTAL, COMPLETE, at/below thyroid</text><text x="80" y="304" class="t-keylbl">Mechanism:</text><text x="220" y="304" class="t-keyval">Venous + carotid compression → asphyxia</text><text x="80" y="336" class="t-keylbl">Hyoid #:</text><text x="180" y="336" class="t-keyval">~30-40% (greater horn)</text><text x="80" y="368" class="t-keylbl">PYQ context:</text><text x="220" y="368" class="t-keyval">"horizontal ligature, no salivary dribbling"</text><text x="80" y="390" class="t-keyval">→ ligature strangulation (NEET-PG 2022)</text><circle class="ic" cx="520" cy="138" r="14"/><text class="t-info" x="520" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-throttling"><rect class="body-white" x="570" y="120" width="490" height="290" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 584,120 H 1046 A 14,14 0 0 1 1060,134 V 195 H 570 V 134 A 14,14 0 0 1 584,120 Z" fill="url(#gOrange)"/><text x="590" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">✋ 2. Throttling (Manual)</text><text x="590" y="240" class="t-keylbl">Agent:</text><text x="670" y="240" class="t-keyval">HANDS at the neck</text><text x="590" y="272" class="t-keylbl">Marks:</text><text x="670" y="272" class="t-keyval">Multiple curved abrasions, bruises (finger nails)</text><text x="590" y="304" class="t-keylbl">Hand pattern:</text><text x="730" y="304" class="t-keyval">Thumb on one side, 4 fingers on opposite</text><text x="590" y="336" class="t-keylbl">Hyoid #:</text><text x="690" y="336" class="t-keyval">MOST COMMON site of hyoid fracture</text><text x="590" y="368" class="t-keylbl">Internal:</text><text x="690" y="368" class="t-keyval">Deep bruising of cricoid + thyroid cartilages</text><text x="590" y="390" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Always HOMICIDAL — self-throttling impossible</text><circle class="ic" cx="1040" cy="138" r="14"/><text class="t-info" x="1040" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-bansdola"><rect class="body-white" x="1080" y="120" width="460" height="290" rx="14"/><path d="M 1094,120 H 1526 A 14,14 0 0 1 1540,134 V 195 H 1080 V 134 A 14,14 0 0 1 1094,120 Z" fill="url(#gPurple)"/><text x="1100" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🪵 3. Bansdola</text><text x="1100" y="240" class="t-keylbl">Method:</text><text x="1190" y="240" class="t-keyval">Two WOODEN STICKS (or bamboo)</text><text x="1100" y="262" class="t-keyval">placed on either side of neck</text><text x="1100" y="284" class="t-keyval">+ tied/squeezed together</text><text x="1100" y="320" class="t-keylbl">Mark:</text><text x="1170" y="320" class="t-keyval">Two parallel linear bruises</text><text x="1100" y="356" class="t-keylbl">PYQ 2016:</text><text x="1200" y="356" class="t-keyval">"Bansdola is a form of</text><text x="1100" y="378" class="t-keyval">strangulation by — WOODEN STICKS"</text><circle class="ic" cx="1510" cy="138" r="14"/><text class="t-info" x="1510" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-garroting"><rect class="body-white" x="60" y="430" width="490" height="290" rx="14"/><path d="M 74,430 H 536 A 14,14 0 0 1 550,444 V 505 H 60 V 444 A 14,14 0 0 1 74,430 Z" fill="url(#gBlue)"/><text x="80" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🪢 4. Garroting (Spanish)</text><text x="80" y="550" class="t-keylbl">Method:</text><text x="170" y="550" class="t-keyval">Ligature thrown from BEHIND</text><text x="80" y="572" class="t-keyval">+ tightened by a STICK (windlass / tourniquet)</text><text x="80" y="608" class="t-keylbl">Origin:</text><text x="160" y="608" class="t-keyval">Spanish judicial execution method</text><text x="80" y="640" class="t-keylbl">Mark:</text><text x="150" y="640" class="t-keyval">Single horizontal, complete</text><text x="80" y="672" class="t-keylbl">Always:</text><text x="170" y="672" class="t-keyval">HOMICIDAL (sneak attack from behind)</text><circle class="ic" cx="520" cy="448" r="14"/><text class="t-info" x="520" y="454" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-mugging"><rect class="body-white" x="570" y="430" width="490" height="290" rx="14"/><path d="M 584,430 H 1046 A 14,14 0 0 1 1060,444 V 505 H 570 V 444 A 14,14 0 0 1 584,430 Z" fill="url(#gGreen)"/><text x="590" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">💪 5. Mugging (Chokehold)</text><text x="590" y="550" class="t-keylbl">Method:</text><text x="680" y="550" class="t-keyval">BEND OF ELBOW around neck from behind</text><text x="590" y="586" class="t-keylbl">Mark:</text><text x="660" y="586" class="t-keyval">Often absent (broad surface — no impression)</text><text x="590" y="618" class="t-keylbl">Mechanism:</text><text x="730" y="618" class="t-keyval">Carotid compression → cerebral hypoxia</text><text x="590" y="650" class="t-keylbl">Context:</text><text x="680" y="650" class="t-keyval">Robbery (street mugging) · police restraint</text><text x="590" y="682" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Hard to prove on autopsy — relies on circumstance</text><circle class="ic" cx="1040" cy="448" r="14"/><text class="t-info" x="1040" y="454" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-palmar"><rect class="body-white" x="1080" y="430" width="460" height="290" rx="14"/><path d="M 1094,430 H 1526 A 14,14 0 0 1 1540,444 V 505 H 1080 V 444 A 14,14 0 0 1 1094,430 Z" fill="url(#gGrey)"/><text x="1100" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🖐️ 6. Palmar Strangulation</text><text x="1100" y="550" class="t-keylbl">Method:</text><text x="1190" y="550" class="t-keyval">Heel of palm on front of neck,</text><text x="1100" y="572" class="t-keyval">pressing inward + back</text><text x="1100" y="608" class="t-keylbl">Target:</text><text x="1170" y="608" class="t-keyval">Crushes larynx / trachea</text><text x="1100" y="640" class="t-keylbl">Mark:</text><text x="1170" y="640" class="t-keyval">Bruise on anterior neck</text><text x="1100" y="672" class="t-keylbl">Context:</text><text x="1190" y="672" class="t-keyval">Domestic violence, ambush</text><circle class="ic" cx="1510" cy="448" r="14"/><text class="t-info" x="1510" y="454" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="740" width="1480" height="160" rx="14" fill="url(#gBlue)" filter="url(#cardShadow)"/><text x="800" y="784" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white" text-anchor="middle">🎯 Strangulation — Universal Features</text><text x="100" y="824" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Almost always HOMICIDAL — exception: rare accidental (autoerotic, scarf caught in machine)</text><text x="100" y="850" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Face MARKEDLY congested + cyanosed (one or both carotids occluded for shorter time)</text><text x="100" y="876" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Pronounced asphyxial stigmata · marked Tardieu spots · severe pulmonary oedema</text>

<rect x="60" y="920" width="1480" height="60" rx="10" fill="url(#gRed)"/><text x="800" y="958" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">⚖️ "LiTh-BaGa-MuPa" — Ligature · Throttling · Bansdola · Garroting · Mugging · Palmar</text>
</svg>`,

VA06: `<svg viewBox="0 0 1600 900" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">PM Findings in Strangulation</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">External: face + ligature/hand marks · Internal: neck + asphyxial signs MORE pronounced than hanging</text>

<g data-node-id="str-pm-face"><rect class="body-white" x="60" y="120" width="740" height="320" rx="14"/><path d="M 74,120 H 786 A 14,14 0 0 1 800,134 V 180 H 60 V 134 A 14,14 0 0 1 74,120 Z" fill="url(#gBlue)"/><text x="90" y="160" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">👤 External — Face</text><text x="90" y="220" class="t-keylbl">Face:</text><text x="160" y="220" class="t-keyval">MARKEDLY congested + cyanosed (always)</text><text x="90" y="252" class="t-keylbl">Eyes:</text><text x="160" y="252" class="t-keyval">Bulging, pupils dilated; numerous conjunctival petechiae</text><text x="90" y="284" class="t-keylbl">Tongue:</text><text x="180" y="284" class="t-keyval">Protruded, swollen, bitten</text><text x="90" y="316" class="t-keylbl">Lips/ears:</text><text x="200" y="316" class="t-keyval">Cyanosed</text><text x="90" y="348" class="t-keylbl">Bleeding:</text><text x="190" y="348" class="t-keyval">From mouth/nose/ears in severe cases</text><text x="90" y="380" class="t-keylbl">No salivary dribbling:</text><text x="290" y="380" class="t-keyval">(unlike hanging) — important DD point</text><text x="90" y="410" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">More dramatic than hanging due to one-sided occlusion + struggle.</text><circle class="ic" cx="770" cy="138" r="14"/><text class="t-info" x="770" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-pm-mark"><rect class="body-white" x="820" y="120" width="720" height="320" rx="14"/><path d="M 834,120 H 1526 A 14,14 0 0 1 1540,134 V 180 H 820 V 134 A 14,14 0 0 1 834,120 Z" fill="url(#gRed)"/><text x="850" y="160" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🪢 External — Mark on Neck</text><text x="850" y="220" class="t-keylbl">Ligature mark:</text><text x="1000" y="220" class="t-keyval"><strong>HORIZONTAL</strong>, COMPLETE, AT/BELOW thyroid</text><text x="850" y="252" class="t-keylbl">Throttling marks:</text><text x="1020" y="252" class="t-keyval">Curved abrasions (finger nails) + bruises</text><text x="850" y="284" class="t-keylbl">Hand pattern:</text><text x="980" y="284" class="t-keyval">Thumb mark on one side, 4 finger marks on other</text><text x="850" y="316" class="t-keylbl">Bansdola:</text><text x="940" y="316" class="t-keyval">Two parallel linear bruises</text><text x="850" y="348" class="t-keylbl">Vital reaction:</text><text x="990" y="348" class="t-keyval">PRONOUNCED bruising, oedema, abrasions</text><text x="850" y="380" class="t-keylbl">Defence wounds:</text><text x="1010" y="380" class="t-keyval">On hands, forearms, face (sign of struggle)</text><circle class="ic" cx="1510" cy="138" r="14"/><text class="t-info" x="1510" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-pm-internal"><rect class="body-white" x="60" y="460" width="740" height="320" rx="14"/><path d="M 74,460 H 786 A 14,14 0 0 1 800,474 V 520 H 60 V 474 A 14,14 0 0 1 74,460 Z" fill="url(#gOrange)"/><text x="90" y="500" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🔬 Internal — Neck Dissection</text><text x="90" y="560" class="t-keylbl">Subcutaneous tissue:</text><text x="290" y="560" class="t-keyval">EXTENSIVE haemorrhage + bruising</text><text x="90" y="592" class="t-keylbl">Strap muscles:</text><text x="240" y="592" class="t-keyval">Sternomastoid + omohyoid haemorrhage</text><text x="90" y="624" class="t-keylbl">Hyoid bone:</text><text x="220" y="624" class="t-keyval">FRACTURE more common (~30-40%, esp. throttling)</text><text x="90" y="656" class="t-keylbl">Cartilages:</text><text x="200" y="656" class="t-keyval">Thyroid + cricoid fracture / bruising</text><text x="90" y="688" class="t-keylbl">Trachea/larynx:</text><text x="240" y="688" class="t-keyval">Congestion, oedema, mucosal abrasion</text><text x="90" y="720" class="t-keylbl">Carotid sheath:</text><text x="240" y="720" class="t-keyval">Bruising; rarely intimal tear</text><text x="90" y="752" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Internal injuries MORE marked than in hanging.</text><circle class="ic" cx="770" cy="478" r="14"/><text class="t-info" x="770" y="484" text-anchor="middle">ⓘ</text></g>

<g data-node-id="str-pm-asphyxial"><rect class="body-white" x="820" y="460" width="720" height="320" rx="14"/><path d="M 834,460 H 1526 A 14,14 0 0 1 1540,474 V 520 H 820 V 474 A 14,14 0 0 1 834,460 Z" fill="url(#gPurple)"/><text x="850" y="500" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🫁 Internal — Asphyxial Signs (MARKED)</text><text x="850" y="560" class="t-keylbl">Petechiae:</text><text x="970" y="560" class="t-keyval">Numerous Tardieu spots — pleura, pericardium</text><text x="850" y="592" class="t-keylbl">Lungs:</text><text x="930" y="592" class="t-keyval">Markedly congested, oedematous, sub-pleural petechiae</text><text x="850" y="624" class="t-keylbl">Heart:</text><text x="930" y="624" class="t-keyval">Right side distended with dark fluid blood</text><text x="850" y="656" class="t-keylbl">Brain:</text><text x="930" y="656" class="t-keyval">Severely congested + oedematous</text><text x="850" y="688" class="t-keylbl">Visceral congestion:</text><text x="1030" y="688" class="t-keyval">Universal — liver, kidneys, spleen</text><text x="850" y="720" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Asphyxial stigmata are typically MORE pronounced than hanging (slower death).</text><circle class="ic" cx="1510" cy="478" r="14"/><text class="t-info" x="1510" y="484" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="800" width="1480" height="60" rx="10" fill="url(#gGreen)"/><text x="800" y="838" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">🎯 Strangulation findings = hanging findings × MARKED + horizontal mark + no salivary dribbling + defence wounds</text>
</svg>`,

VA07: `<svg viewBox="0 0 1600 1000" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">Hyoid Bone Fractures in Asphyxial Deaths</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">Hyoid = U-shaped bone at C3 level · 3 fracture patterns based on direction of compression</text>

<g data-node-id="hyoid-anatomy"><rect x="60" y="120" width="1480" height="200" rx="14" fill="url(#gBlue)" filter="url(#cardShadow)"/><text x="800" y="160" font-family="Inter,system-ui,sans-serif" font-size="22" font-weight="800" fill="white" text-anchor="middle">🦴 Hyoid Bone — Anatomy</text><text x="100" y="200" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• <strong>U-shaped bone</strong> at the level of <strong>C3 vertebra</strong></text><text x="100" y="226" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• Suspended from styloid process by stylohyoid ligament · attached to thyroid cartilage</text><text x="100" y="252" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• Parts: 1 <strong>BODY</strong> (anterior) · 2 <strong>GREATER cornu</strong> (lateral, longer) · 2 <strong>LESSER cornu</strong> (superior, shorter)</text><text x="100" y="278" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• Ossification: greater cornu fuses with body in middle age — younger hyoid is more flexible (less fracture)</text><text x="100" y="304" font-family="Inter,system-ui,sans-serif" font-size="13" font-weight="500" fill="rgba(255,255,255,0.75)">⭐ Fracture is more common in older individuals (post-fusion); rare under age 25.</text><circle class="ic" cx="1510" cy="140" r="14"/><text class="t-info" x="1510" y="146" text-anchor="middle">ⓘ</text></g>

<g data-node-id="hyoid-inout"><rect class="body-white" x="60" y="340" width="490" height="360" rx="14"/><path d="M 74,340 H 536 A 14,14 0 0 1 550,354 V 410 H 60 V 354 A 14,14 0 0 1 74,340 Z" fill="url(#gGreen)"/><text x="80" y="390" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">🔃 1. Inward Compression (IN-and-OUT)</text><text x="80" y="450" class="t-keylbl">Direction:</text><text x="190" y="450" class="t-keyval">Both greater cornua pushed INWARD</text><text x="80" y="482" class="t-keylbl">Fracture site:</text><text x="220" y="482" class="t-keyval">Body or junction of body + greater cornu</text><text x="80" y="514" class="t-keylbl">Outer periosteum:</text><text x="270" y="514" class="t-keyval">TORN (on outer surface)</text><text x="80" y="546" class="t-keylbl">Inner periosteum:</text><text x="270" y="546" class="t-keyval">INTACT</text><text x="80" y="580" class="t-keylbl">Seen in:</text><text x="180" y="580" class="t-keyval">THROTTLING — bilateral compression by hands</text><text x="80" y="620" class="t-keylbl">Vital reaction:</text><text x="240" y="620" class="t-keyval">Haemorrhage in surrounding tissue</text><text x="80" y="658" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Most common fracture pattern in throttling.</text><circle class="ic" cx="520" cy="358" r="14"/><text class="t-info" x="520" y="364" text-anchor="middle">ⓘ</text></g>

<g data-node-id="hyoid-outin"><rect class="body-white" x="570" y="340" width="490" height="360" rx="14"/><path d="M 584,340 H 1046 A 14,14 0 0 1 1060,354 V 410 H 570 V 354 A 14,14 0 0 1 584,340 Z" fill="url(#gOrange)"/><text x="590" y="390" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">🔄 2. Outward Compression (OUT-and-IN)</text><text x="590" y="450" class="t-keylbl">Direction:</text><text x="700" y="450" class="t-keyval">Cornua splay OUTWARD</text><text x="590" y="482" class="t-keylbl">Mechanism:</text><text x="730" y="482" class="t-keyval">Ligature pulls upward → splaying force</text><text x="590" y="514" class="t-keylbl">Fracture site:</text><text x="730" y="514" class="t-keyval">Greater cornu tip</text><text x="590" y="546" class="t-keylbl">Outer periosteum:</text><text x="780" y="546" class="t-keyval">INTACT</text><text x="590" y="578" class="t-keylbl">Inner periosteum:</text><text x="780" y="578" class="t-keyval">TORN</text><text x="590" y="612" class="t-keylbl">Seen in:</text><text x="690" y="612" class="t-keyval">HANGING with high knot position</text><text x="590" y="650" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Diagnostic of hanging — direction differentiates from throttling.</text><circle class="ic" cx="1040" cy="358" r="14"/><text class="t-info" x="1040" y="364" text-anchor="middle">ⓘ</text></g>

<g data-node-id="hyoid-ap"><rect class="body-white" x="1080" y="340" width="460" height="360" rx="14"/><path d="M 1094,340 H 1526 A 14,14 0 0 1 1540,354 V 410 H 1080 V 354 A 14,14 0 0 1 1094,340 Z" fill="url(#gRed)"/><text x="1100" y="390" font-family="Inter,system-ui,sans-serif" font-size="18" font-weight="800" fill="white">↕️ 3. Antero-Posterior</text><text x="1100" y="450" class="t-keylbl">Direction:</text><text x="1210" y="450" class="t-keyval">Cornua pushed BACKWARDS</text><text x="1100" y="482" class="t-keylbl">Mechanism:</text><text x="1240" y="482" class="t-keyval">Direct anterior force</text><text x="1100" y="514" class="t-keyval">(palmar strangulation, direct blow)</text><text x="1100" y="550" class="t-keylbl">Fracture site:</text><text x="1240" y="550" class="t-keyval">Variable; can be body</text><text x="1100" y="582" class="t-keylbl">Seen in:</text><text x="1190" y="582" class="t-keyval">Palmar strangulation,</text><text x="1100" y="604" class="t-keyval">blunt force trauma to neck</text><text x="1100" y="640" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Less common pattern; needs direct frontal force.</text><circle class="ic" cx="1510" cy="358" r="14"/><text class="t-info" x="1510" y="364" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="720" width="1480" height="160" rx="14" fill="url(#gPurple)" filter="url(#cardShadow)"/><text x="800" y="760" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white" text-anchor="middle">📊 Hyoid Fracture — Frequency by Cause</text><text x="100" y="798" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• <strong>Throttling</strong> — fracture in <strong>~30-40 %</strong> · greater cornu (in-and-out pattern) · most common cause of hyoid #</text><text x="100" y="824" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• <strong>Ligature strangulation</strong> — fracture in <strong>~20-30 %</strong> · variable site</text><text x="100" y="850" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="rgba(255,255,255,0.92)">• <strong>Hanging</strong> — fracture in <strong>&lt; 30 %</strong> · greater cornu (out-and-in) · less common than strangulation</text>

<rect x="60" y="900" width="1480" height="50" rx="10" fill="url(#gOrange)"/><text x="800" y="932" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">🎯 Throttling = highest hyoid # rate · pattern: greater cornu, inward compression, outer periosteum torn</text>
</svg>`,

VA08: `<svg viewBox="0 0 1600 1100" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">Suffocation Group — 5 Mechanisms</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">Obstruction of air passages WITHOUT force on the neck · mostly accidental, some homicidal</text>

<g data-node-id="suf-smothering"><rect class="body-white" x="60" y="120" width="490" height="290" rx="14"/><path d="M 74,120 H 536 A 14,14 0 0 1 550,134 V 195 H 60 V 134 A 14,14 0 0 1 74,120 Z" fill="url(#gBlue)"/><text x="80" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">😷 1. Smothering</text><text x="80" y="240" class="t-keylbl">Definition:</text><text x="190" y="240" class="t-keyval">Closing of MOUTH + NOSE externally</text><text x="80" y="272" class="t-keylbl">Agents:</text><text x="160" y="272" class="t-keyval">Pillow, hand, plastic bag, cloth, soft tissue</text><text x="80" y="304" class="t-keylbl">PM findings:</text><text x="220" y="304" class="t-keyval">Bruises / abrasions around mouth + nose</text><text x="80" y="336" class="t-keylbl">Common in:</text><text x="220" y="336" class="t-keyval">Infants (overlying / SIDS DD), homicide</text><text x="80" y="368" class="t-keylbl">Plastic bag:</text><text x="220" y="368" class="t-keyval">Suicide (terminally ill, depression)</text><circle class="ic" cx="520" cy="138" r="14"/><text class="t-info" x="520" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="suf-gagging"><rect class="body-white" x="570" y="120" width="490" height="290" rx="14"/><path d="M 584,120 H 1046 A 14,14 0 0 1 1060,134 V 195 H 570 V 134 A 14,14 0 0 1 584,120 Z" fill="url(#gOrange)"/><text x="590" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🤐 2. Gagging</text><text x="590" y="240" class="t-keylbl">Definition:</text><text x="700" y="240" class="t-keyval">Material forced INTO mouth</text><text x="590" y="272" class="t-keyval">to block oral cavity / pharynx</text><text x="590" y="304" class="t-keylbl">Agents:</text><text x="670" y="304" class="t-keyval">Cloth, handkerchief, paper, tape</text><text x="590" y="336" class="t-keylbl">PM findings:</text><text x="730" y="336" class="t-keyval">Foreign material in oropharynx; abrasions</text><text x="590" y="358" class="t-keyval">on lips, teeth marks on cheek mucosa</text><text x="590" y="390" class="t-keylbl">Common in:</text><text x="730" y="390" class="t-keyval">Burglary victims (silenced + restrained)</text><circle class="ic" cx="1040" cy="138" r="14"/><text class="t-info" x="1040" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="suf-choking"><rect class="body-white" x="1080" y="120" width="460" height="290" rx="14"/><path d="M 1094,120 H 1526 A 14,14 0 0 1 1540,134 V 195 H 1080 V 134 A 14,14 0 0 1 1094,120 Z" fill="url(#gRed)"/><text x="1100" y="170" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🍞 3. Choking</text><text x="1100" y="240" class="t-keylbl">Definition:</text><text x="1210" y="240" class="t-keyval">INTERNAL obstruction of</text><text x="1100" y="262" class="t-keyval">airway by foreign body</text><text x="1100" y="298" class="t-keylbl">Bolus death:</text><text x="1230" y="298" class="t-keyval">Food bolus stuck at larynx</text><text x="1100" y="320" class="t-keyval">— vagal reflex → sudden cardiac arrest</text><text x="1100" y="356" class="t-keylbl">PM:</text><text x="1160" y="356" class="t-keyval">Foreign body in larynx/trachea</text><text x="1100" y="388" class="t-keylbl">Common in:</text><text x="1220" y="388" class="t-keyval">Elderly, drunk, dementia</text><circle class="ic" cx="1510" cy="138" r="14"/><text class="t-info" x="1510" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="suf-traumatic"><rect class="body-white" x="60" y="430" width="490" height="290" rx="14"/><path d="M 74,430 H 536 A 14,14 0 0 1 550,444 V 505 H 60 V 444 A 14,14 0 0 1 74,430 Z" fill="url(#gPurple)"/><text x="80" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">💥 4. Traumatic Asphyxia</text><text x="80" y="550" class="t-keylbl">Definition:</text><text x="190" y="550" class="t-keyval">External compression of CHEST</text><text x="80" y="572" class="t-keyval">prevents respiratory movements</text><text x="80" y="608" class="t-keylbl">Causes:</text><text x="170" y="608" class="t-keyval">Crowd crush, stampede, building collapse,</text><text x="80" y="630" class="t-keyval">vehicle pinning, industrial accident</text><text x="80" y="664" class="t-keylbl">Cardinal sign:</text><text x="240" y="664" class="t-keyval"><strong>Masque ecchymotique</strong> — deep blue</text><text x="80" y="686" class="t-keyval">discolouration of face, neck, upper chest</text><circle class="ic" cx="520" cy="448" r="14"/><text class="t-info" x="520" y="454" text-anchor="middle">ⓘ</text></g>

<g data-node-id="suf-overlying"><rect class="body-white" x="570" y="430" width="490" height="290" rx="14"/><path d="M 584,430 H 1046 A 14,14 0 0 1 1060,444 V 505 H 570 V 444 A 14,14 0 0 1 584,430 Z" fill="url(#gGreen)"/><text x="590" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">👶 5. Overlying / SIDS DD</text><text x="590" y="550" class="t-keylbl">Overlying:</text><text x="690" y="550" class="t-keyval">Adult accidentally smothers infant</text><text x="590" y="572" class="t-keyval">while co-sleeping (mostly accidental)</text><text x="590" y="608" class="t-keylbl">SIDS:</text><text x="650" y="608" class="t-keyval">Sudden Infant Death Syndrome — unexplained</text><text x="590" y="630" class="t-keyval">death of infant &lt; 1 yr (DD for overlying)</text><text x="590" y="666" class="t-keylbl">Distinguish:</text><text x="720" y="666" class="t-keyval">Detailed scene reconstruction + autopsy needed</text><text x="590" y="696" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">SIDS detailed in Ch 20 (Infant Deaths).</text><circle class="ic" cx="1040" cy="448" r="14"/><text class="t-info" x="1040" y="454" text-anchor="middle">ⓘ</text></g>

<g data-node-id="suf-burking"><rect class="body-white" x="1080" y="430" width="460" height="290" rx="14"/><path d="M 1094,430 H 1526 A 14,14 0 0 1 1540,444 V 505 H 1080 V 444 A 14,14 0 0 1 1094,430 Z" fill="url(#gGrey)"/><text x="1100" y="480" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">⚖️ 6. Burking</text><text x="1100" y="550" class="t-keylbl">Definition:</text><text x="1210" y="550" class="t-keyval">Combined smothering +</text><text x="1100" y="572" class="t-keyval">chest compression</text><text x="1100" y="608" class="t-keylbl">Method:</text><text x="1180" y="608" class="t-keyval">Sitting on chest + closing</text><text x="1100" y="630" class="t-keyval">mouth/nose</text><text x="1100" y="666" class="t-keylbl">Named after:</text><text x="1230" y="666" class="t-keyval">William Burke (1828 Edinburgh)</text><text x="1100" y="688" class="t-keyval">— sold bodies to anatomy school</text><circle class="ic" cx="1510" cy="448" r="14"/><text class="t-info" x="1510" y="454" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="740" width="1480" height="180" rx="14" fill="url(#gBlue)" filter="url(#cardShadow)"/><text x="800" y="780" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white" text-anchor="middle">⚙️ Common Features in Suffocation Group</text><text x="100" y="820" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Classical asphyxial signs (Tardieu spots, cyanosis, congestion) usually present</text><text x="100" y="846" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Marks AROUND or INSIDE mouth/nose · NO ligature mark on neck</text><text x="100" y="872" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Foreign body may be retrieved on autopsy (gagging, choking)</text><text x="100" y="898" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)">• Diagnosis often relies on scene reconstruction + circumstances</text>

<rect x="60" y="940" width="1480" height="50" rx="10" fill="url(#gOrange)"/><text x="800" y="972" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">🎯 Masque ecchymotique = pathognomonic for traumatic asphyxia (crush)</text>
</svg>`,

VA09: `<svg viewBox="0 0 1600 1100" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">Drowning — Types &amp; Mechanism</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">Asphyxia from immersion of mouth/nose in fluid · 4 types based on mechanism</text>

<g data-node-id="drown-definition"><rect class="nbcr" x="60" y="120" width="1480" height="100" rx="14"/><text x="90" y="158" font-family="Inter,system-ui,sans-serif" font-size="16" font-weight="800" fill="#8B6914">💧 DROWNING</text><text x="90" y="188" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="500" fill="#5C4810">= Death by asphyxia caused by immersion of mouth and nose in fluid medium · fluid fills the airways preventing gas exchange · "fluid" can be water, sewage, mud, oil, blood, etc.</text><circle class="ic" cx="1500" cy="140" r="14"/><text class="t-info" x="1500" y="146" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-wet"><rect class="body-white" x="60" y="250" width="740" height="290" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 74,250 H 786 A 14,14 0 0 1 800,264 V 320 H 60 V 264 A 14,14 0 0 1 74,250 Z" fill="url(#gBlue)"/><text x="90" y="290" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🌊 1. WET Drowning (~90%)</text><text x="90" y="350" class="t-keylbl">Mechanism:</text><text x="240" y="350" class="t-keyval">Fluid aspirated into LUNGS</text><text x="90" y="382" class="t-keylbl">Fresh water:</text><text x="220" y="382" class="t-keyval">Hypotonic → into circulation → haemodilution</text><text x="110" y="404" class="t-keyval">→ haemolysis → hyperkalaemia → VF + death (5-10 min)</text><text x="90" y="436" class="t-keylbl">Sea water:</text><text x="200" y="436" class="t-keyval">Hypertonic → water OUT of circulation → pulmonary</text><text x="110" y="458" class="t-keyval">oedema → hypovolaemia + hypoxia → death (8-12 min)</text><text x="90" y="494" class="t-keylbl">Most common type</text><circle class="ic" cx="770" cy="268" r="14"/><text class="t-info" x="770" y="274" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-dry"><rect class="body-white" x="820" y="250" width="720" height="290" rx="14"/><path d="M 834,250 H 1526 A 14,14 0 0 1 1540,264 V 320 H 820 V 264 A 14,14 0 0 1 834,250 Z" fill="url(#gGreen)"/><text x="850" y="290" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🚫 2. DRY Drowning (~10%)</text><text x="850" y="350" class="t-keylbl">Mechanism:</text><text x="1000" y="350" class="t-keyval">Sudden LARYNGOSPASM at first contact</text><text x="870" y="372" class="t-keyval">with water → larynx closes → asphyxia → death</text><text x="850" y="404" class="t-keylbl">Lungs:</text><text x="920" y="404" class="t-keyval">REMAIN DRY at autopsy (no fluid)</text><text x="850" y="436" class="t-keylbl">Common in:</text><text x="980" y="436" class="t-keyval">Cold water entry, panic, intoxication</text><text x="850" y="468" class="t-keylbl">Diagnosis:</text><text x="960" y="468" class="t-keyval">Difficult — by exclusion + history</text><text x="850" y="500" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Tip: Watch for cyanosed face, foaming at mouth despite dry lungs.</text><circle class="ic" cx="1510" cy="268" r="14"/><text class="t-info" x="1510" y="274" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-secondary"><rect class="body-white" x="60" y="560" width="740" height="290" rx="14"/><path d="M 74,560 H 786 A 14,14 0 0 1 800,574 V 630 H 60 V 574 A 14,14 0 0 1 74,560 Z" fill="url(#gOrange)"/><text x="90" y="600" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">⏱️ 3. SECONDARY (Post-immersion)</text><text x="90" y="660" class="t-keylbl">Time:</text><text x="160" y="660" class="t-keyval">Death HOURS to DAYS after rescue</text><text x="90" y="692" class="t-keylbl">Mechanism:</text><text x="240" y="692" class="t-keyval">Aspirated water damages surfactant →</text><text x="110" y="714" class="t-keyval">delayed pulmonary oedema · ARDS · pneumonia</text><text x="90" y="750" class="t-keylbl">Risk factors:</text><text x="240" y="750" class="t-keyval">Aspiration of large volume, cold water,</text><text x="110" y="772" class="t-keyval">prolonged immersion, fresh water</text><text x="90" y="804" class="t-keylbl">Management:</text><text x="250" y="804" class="t-keyval">Observe rescued drowning victims ≥ 24h</text><circle class="ic" cx="770" cy="578" r="14"/><text class="t-info" x="770" y="584" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-immersion"><rect class="body-white" x="820" y="560" width="720" height="290" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 834,560 H 1526 A 14,14 0 0 1 1540,574 V 630 H 820 V 574 A 14,14 0 0 1 834,560 Z" fill="url(#gPurple)"/><text x="850" y="600" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">⚡ 4. IMMERSION (HYDROCUTION)</text><text x="850" y="660" class="t-keylbl">Definition:</text><text x="980" y="660" class="t-keyval">SUDDEN DEATH on entering cold water</text><text x="850" y="692" class="t-keylbl">Mechanism:</text><text x="1000" y="692" class="t-keyval"><strong>VAGAL INHIBITION</strong> — cold water on</text><text x="870" y="714" class="t-keyval">skin / hitting epigastrium triggers reflex cardiac arrest</text><text x="850" y="750" class="t-keylbl">Time to death:</text><text x="1010" y="750" class="t-keyval">Within SECONDS to 1-2 minutes</text><text x="850" y="782" class="t-keylbl">Lungs:</text><text x="930" y="782" class="t-keyval">May be dry (death too fast to aspirate)</text><text x="850" y="814" class="t-keylbl">Synonyms:</text><text x="970" y="814" class="t-keyval">"Hydrocution" · "Cold shock"</text><circle class="ic" cx="1510" cy="578" r="14"/><text class="t-info" x="1510" y="584" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-stages"><rect x="60" y="870" width="1480" height="200" rx="14" fill="url(#gGrey)" filter="url(#cardShadow)"/><text x="800" y="912" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white" text-anchor="middle">⏱️ 5 Stages of Drowning (in wet drowning)</text><text x="100" y="950" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)"><strong>1. Surprise</strong> (5-10 sec) — sudden immersion → reflex inspiration → water enters airways</text><text x="100" y="976" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)"><strong>2. Resistance / Struggle</strong> (1-2 min) — breath-holding · violent struggle · panic · efforts to rise</text><text x="100" y="1002" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)"><strong>3. Deep respiration phase</strong> (1-2 min) — involuntary deep breaths → massive water inhalation</text><text x="100" y="1028" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)"><strong>4. Convulsions / exhaustion</strong> (1 min) — generalised seizures · hypoxia · unconsciousness</text><text x="100" y="1054" font-family="Inter,system-ui,sans-serif" font-size="14" fill="rgba(255,255,255,0.92)"><strong>5. Death</strong> — total respiratory + cardiac arrest · typical duration ~5 min</text><circle class="ic" cx="1510" cy="890" r="14"/><text class="t-info" x="1510" y="896" text-anchor="middle">ⓘ</text></g>
</svg>`,

VA10: `<svg viewBox="0 0 1600 1100" xmlns="http://www.w3.org/2000/svg" class="diagram-svg">
\${STYLE}
<text class="t-title" x="800" y="50" text-anchor="middle">PM Findings in Drowning</text>
<text class="t-sub" x="800" y="80" text-anchor="middle">External: cutis anserina, washerwoman's hand, champignon froth · Internal: emphysema aquosum, diatoms</text>

<g data-node-id="drown-pm-external"><rect class="body-white" x="60" y="120" width="740" height="380" rx="14"/><path d="M 74,120 H 786 A 14,14 0 0 1 800,134 V 180 H 60 V 134 A 14,14 0 0 1 74,120 Z" fill="url(#gBlue)"/><text x="90" y="160" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">👤 External Findings</text><text x="90" y="220" class="t-keylbl">Face:</text><text x="160" y="220" class="t-keyval">Pale (early) or cyanosed (late); puffy</text><text x="90" y="252" class="t-keylbl">Mouth/nostrils:</text><text x="270" y="252" class="t-keyval"><strong>Champignon mushroom froth</strong></text><text x="110" y="274" class="t-keyval">(fine, white-pinkish, persistent — pathognomonic)</text><text x="90" y="310" class="t-keylbl">Eyes:</text><text x="160" y="310" class="t-keyval">Open; conjunctival haemorrhages</text><text x="90" y="342" class="t-keylbl">Cutis anserina (goose-skin):</text><text x="330" y="342" class="t-keyval">Erection of hair follicles</text><text x="110" y="364" class="t-keyval">from cold + rigor of arrectores pilorum (NON-specific)</text><text x="90" y="400" class="t-keylbl">Washerwoman's hand:</text><text x="290" y="400" class="t-keyval">Wrinkling + sodden whitening of</text><text x="110" y="422" class="t-keyval">palms and soles (after &gt; 2 hours immersion)</text><text x="90" y="458" class="t-keylbl">Clenched fists:</text><text x="240" y="458" class="t-keyval">Cadaveric spasm — may grasp weeds, mud</text><circle class="ic" cx="770" cy="138" r="14"/><text class="t-info" x="770" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-pm-lungs"><rect class="body-white" x="820" y="120" width="720" height="380" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 834,120 H 1526 A 14,14 0 0 1 1540,134 V 180 H 820 V 134 A 14,14 0 0 1 834,120 Z" fill="url(#gRed)"/><text x="850" y="160" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🫁 Lungs — Key Findings</text><text x="850" y="220" class="t-keylbl">Emphysema aquosum:</text><text x="1080" y="220" class="t-keyval">Lungs ballooned, heavy,</text><text x="870" y="242" class="t-keyval">overlap at midline · pit on pressure</text><text x="850" y="278" class="t-keylbl">Surface:</text><text x="940" y="278" class="t-keyval"><strong>Paltauf haemorrhages</strong> — sub-pleural</text><text x="870" y="300" class="t-keyval">bluish-red haemorrhages (rupture of alveolar capillaries)</text><text x="850" y="336" class="t-keylbl">Cut surface:</text><text x="980" y="336" class="t-keyval">Frothy fluid + blood-stained mucus</text><text x="850" y="368" class="t-keylbl">Airways:</text><text x="940" y="368" class="t-keyval">Fine frothy fluid in trachea, bronchi</text><text x="850" y="400" class="t-keylbl">Stomach:</text><text x="950" y="400" class="t-keyval">Water + sand / silt (swallowed during struggle)</text><text x="850" y="432" class="t-keylbl">Middle ear:</text><text x="980" y="432" class="t-keyval">Haemorrhage (Niles sign — DD: head injury)</text><text x="850" y="464" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Paltauf haemorrhage = relatively specific for drowning.</text><circle class="ic" cx="1510" cy="138" r="14"/><text class="t-info" x="1510" y="144" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-diatom"><rect class="body-white" x="60" y="520" width="740" height="320" rx="14" stroke="#C58A3D" stroke-width="3"/><path d="M 74,520 H 786 A 14,14 0 0 1 800,534 V 580 H 60 V 534 A 14,14 0 0 1 74,520 Z" fill="url(#gGreen)"/><text x="90" y="560" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">🔬 Diatom Test (Gold Standard)</text><text x="90" y="620" class="t-keylbl">Principle:</text><text x="190" y="620" class="t-keyval">Diatoms = microscopic algae in water</text><text x="90" y="650" class="t-keyval">Antemortem drowning → diatoms aspirated into lungs →</text><text x="90" y="672" class="t-keyval">enter circulation via pulmonary capillaries → reach</text><text x="90" y="694" class="t-keyval">distant organs (brain, kidney, bone marrow, sternum)</text><text x="90" y="730" class="t-keylbl">Test:</text><text x="160" y="730" class="t-keyval">Acid-digestion of organs · examine sediment by microscopy</text><text x="90" y="762" class="t-keylbl">Best sample:</text><text x="240" y="762" class="t-keyval">FEMUR BONE MARROW (deep, less contamination)</text><text x="90" y="794" class="t-keylbl">Positive test:</text><text x="240" y="794" class="t-keyval">Diatoms in distant organs ⟹ ANTEMORTEM drowning</text><text x="90" y="822" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">Limitations: false positives (contamination), false negatives (clean water).</text><circle class="ic" cx="770" cy="538" r="14"/><text class="t-info" x="770" y="544" text-anchor="middle">ⓘ</text></g>

<g data-node-id="drown-misc"><rect class="body-white" x="820" y="520" width="720" height="320" rx="14"/><path d="M 834,520 H 1526 A 14,14 0 0 1 1540,534 V 580 H 820 V 534 A 14,14 0 0 1 834,520 Z" fill="url(#gPurple)"/><text x="850" y="560" font-family="Inter,system-ui,sans-serif" font-size="20" font-weight="800" fill="white">📊 Other Useful Tests</text><text x="850" y="620" class="t-keylbl">Gettler test:</text><text x="970" y="620" class="t-keyval">Chloride concentration in L vs R heart blood</text><text x="870" y="642" class="t-keyval">— fresh water drowning: ↑ in L heart</text><text x="850" y="678" class="t-keylbl">Specific gravity test:</text><text x="1040" y="678" class="t-keyval">Blood specific gravity ↓ in fresh-water</text><text x="850" y="710" class="t-keylbl">Strontium test:</text><text x="990" y="710" class="t-keyval">Strontium in blood = sea-water drowning</text><text x="850" y="742" class="t-keylbl">Hydrocution (immersion):</text><text x="1090" y="742" class="t-keyval">Lungs may be DRY</text><text x="870" y="764" class="t-keyval">— sudden vagal arrest before aspiration</text><text x="850" y="800" font-family="Inter,system-ui,sans-serif" font-size="11.5" font-style="italic" fill="#6B7283">In hydrocution, suspect on history + cold water + sudden collapse.</text><circle class="ic" cx="1510" cy="538" r="14"/><text class="t-info" x="1510" y="544" text-anchor="middle">ⓘ</text></g>

<rect x="60" y="860" width="1480" height="60" rx="10" fill="url(#gOrange)"/><text x="800" y="898" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">🎯 Pathognomonic = champignon froth + Paltauf haemorrhages + diatoms in distant organs</text>

<rect x="60" y="940" width="1480" height="60" rx="10" fill="url(#gGrey)"/><text x="800" y="978" font-family="Inter,system-ui,sans-serif" font-size="14" font-weight="700" fill="white" text-anchor="middle">⚠️ DD for body in water: drowning · antemortem injury + body dumped · hydrocution · cardiac death</text>
</svg>`,
};

const NODES_ADD = `,
  'lm-direction': { label: 'Ligature Mark — Direction', info: '<p><strong>Hanging mark:</strong> OBLIQUE — runs upward toward the knot. The most reliable single distinguishing feature.</p><p><strong>Strangulation mark:</strong> HORIZONTAL — encircles the neck level.</p><p>Reason: hanging suspends body weight from a fixed knot above, so the ligature angles up to that point. Strangulation force is applied horizontally around the neck.</p>', tags: ['Oblique vs Horizontal'] },
  'lm-continuity': { label: 'Ligature Mark — Continuity', info: '<p><strong>Hanging mark:</strong> INCOMPLETE — broken at the knot site, because the ligature lifts off the skin at that point.</p><p><strong>Strangulation mark:</strong> COMPLETE — fully encircles the neck, because the ligature is wound around without a single elevated knot.</p>', tags: ['Incomplete vs Complete'] },
  'lm-level': { label: 'Ligature Mark — Level vs Thyroid Cartilage', info: '<p>The thyroid cartilage is the anatomical landmark:</p><ul><li><strong>Hanging:</strong> mark is <strong>ABOVE</strong> the thyroid (typically at level of chin / mandibular angle)</li><li><strong>Strangulation:</strong> mark is <strong>AT or BELOW</strong> the thyroid</li></ul><p>Reason: in hanging, the rising direction places the upper portion of the loop above thyroid.</p>', tags: ['Above vs At/Below'] },
  'lm-texture': { label: 'Ligature Mark — Texture / Pattern', info: '<p>The ligature mark <strong>reproduces the surface pattern</strong> of the constricting agent:</p><ul><li><strong>Rope:</strong> twisted pattern with linear depressions</li><li><strong>Leather belt:</strong> stitching pattern visible</li><li><strong>Dupatta / scarf:</strong> weave pattern</li><li><strong>Electrical cable:</strong> ridges</li><li><strong>Soft cloth:</strong> shallow, broad, often subtle</li></ul><p><strong>Hard ligatures</strong> (rope, cable) leave sharp, deep, parchment-like marks. <strong>Soft ligatures</strong> (silk scarf) may leave only a faint mark — search carefully.</p>', tags: ['Reproduces ligature pattern'] },
  'lm-colour': { label: 'Ligature Mark — Colour', info: '<p><strong>Initially:</strong> pale to yellow-brown.</p><p><strong>After hours-days:</strong> dark brown, parchment-like (dried + shrunken).</p><p><strong>Mechanism of parchmentisation:</strong> Pressure squeezes blood out of the compressed dermis → drying → leathery appearance.</p><p>Parchmentisation is a key sign of vital reaction — confirms ligature applied with significant force.</p>', tags: ['Parchmentisation'] },
  'lm-knot': { label: 'Ligature Mark — Knot Impression', info: '<p>A distinct pressure mark at the knot site, often surrounded by:</p><ul><li>Ecchymosis (vital reaction in antemortem)</li><li>Abrasion / friction marks on edges</li><li>Pattern reflecting knot type</li></ul><p><strong>Typical hanging:</strong> knot posterior (occipital).</p><p><strong>Atypical hanging:</strong> knot lateral or anterior.</p>', tags: ['Pressure point at knot'] },
  'lm-vital': { label: 'Vital Reaction (★ = AM marker)', info: '<p>The single most important determinant of <strong>antemortem</strong> ligature application is <strong>vital reaction</strong> around and beneath the mark.</p><p><strong>Antemortem signs:</strong></p><ul><li>Bruising (ecchymosis) — small haemorrhages in skin / subcutaneous tissue</li><li>Abrasions on edges of the mark</li><li>Oedema and inflammation around the mark</li><li>Sternomastoid muscle haemorrhage on dissection</li><li><strong>Salivary dribbling</strong> from corner of mouth opposite the knot (★ NEET-PG 2016 PYQ)</li></ul><p><strong>Postmortem ligature:</strong> mark is pale, no vital reaction, no haemorrhage in surrounding tissues.</p>', tags: ['★ AM determinant', 'Salivary dribbling = NEET-PG 2016'] },

  'str-ligature': { label: 'Ligature Strangulation', info: '<p>Constriction of neck by a <strong>ligature</strong> (rope, scarf, dupatta, wire, electrical cable) where force is applied by hand (not body weight).</p><p><strong>Ligature mark:</strong> HORIZONTAL, COMPLETE, AT or BELOW thyroid cartilage.</p><p><strong>Mechanism:</strong> Venous + carotid compression → cerebral hypoxia → asphyxia. Slower than complete hanging.</p><p><strong>Hyoid fracture:</strong> ~30-40 % (greater horn).</p><p><strong>NEET-PG 2022 PYQ:</strong> a body with ligature completely encircling the neck, horizontal, below thyroid, with no salivary dribbling → ligature strangulation (not hanging).</p>', tags: ['Most common strangulation', 'NEET-PG 2022 PYQ'] },
  'str-throttling': { label: 'Throttling (Manual Strangulation)', info: '<p>Strangulation by <strong>HANDS</strong> applied directly to the neck.</p><p><strong>Marks:</strong> Multiple curved abrasions (finger nails) + bruises. Classic pattern: thumb mark on one side of neck + 4 finger marks on the opposite side.</p><p><strong>Hyoid fracture:</strong> Most common site of hyoid fracture overall — pattern: greater cornu, in-and-out (inward compression).</p><p><strong>Internal:</strong> Deep bruising of cricoid + thyroid cartilages; sternomastoid muscle haemorrhage.</p><p><strong>Always HOMICIDAL</strong> — self-throttling is impossible because consciousness is lost before sustained force can be applied.</p>', tags: ['Always homicidal', 'Highest hyoid # rate'] },
  'str-bansdola': { label: 'Bansdola Strangulation', info: '<p>An Indian sub-continental method using <strong>two wooden sticks (or bamboo)</strong> placed on either side of the neck, then tied or squeezed together.</p><p><strong>Mark:</strong> Two parallel linear bruises corresponding to the stick edges.</p><p><strong>NEET-PG 2016 PYQ:</strong> "Bansdola is a form of strangulation by — Wooden sticks."</p><p>The word "bans" = bamboo in Hindi.</p>', tags: ['NEET-PG 2016 PYQ', 'Wooden sticks'] },
  'str-garroting': { label: 'Garroting (Spanish)', info: '<p>Strangulation by throwing a <strong>ligature from BEHIND</strong> the victim, then tightening it using a <strong>STICK (windlass / tourniquet)</strong>.</p><p><strong>Origin:</strong> Spanish judicial execution method ("garrote vil").</p><p><strong>Mark:</strong> Single horizontal, complete ligature mark.</p><p><strong>Always HOMICIDAL</strong> — typical sneak attack from behind, often with co-perpetrator.</p>', tags: ['Spanish execution method', 'Sneak attack'] },
  'str-mugging': { label: 'Mugging (Chokehold)', info: '<p>Strangulation by placing the <strong>bend of the elbow around the neck</strong> from behind, pressing inward (carotid sleeper hold).</p><p><strong>Mark:</strong> Often ABSENT — broad surface area distributes force, leaving no clear impression.</p><p><strong>Mechanism:</strong> Carotid compression → cerebral hypoxia → unconsciousness within seconds. Continued pressure → death.</p><p><strong>Context:</strong> Street robbery / mugging. Also used as police restraint hold (controversial — implicated in custodial deaths).</p>', tags: ['Often no neck mark', 'Police restraint'] },
  'str-palmar': { label: 'Palmar Strangulation', info: '<p>Direct pressure with the <strong>heel of the palm</strong> on the front of the neck, pressing inward and backward.</p><p><strong>Target:</strong> Crushes larynx or trachea against cervical spine.</p><p><strong>Mark:</strong> Bruise on anterior neck — often with imprint of palm.</p><p><strong>Context:</strong> Domestic violence, ambush situations, sometimes part of a wider assault.</p>', tags: ['Anterior neck bruise', 'Crushes larynx'] },

  'str-pm-face': { label: 'Strangulation — External Face', info: '<p><strong>Face:</strong> MARKEDLY congested + cyanosed (always — much more pronounced than hanging).</p><p><strong>Eyes:</strong> Bulging; pupils dilated; numerous conjunctival petechiae (Tardieu spots).</p><p><strong>Tongue:</strong> Protruded, swollen, bitten.</p><p><strong>Lips/ears:</strong> Cyanosed.</p><p><strong>Bleeding</strong> from mouth/nose/ears in severe cases.</p><p><strong>No salivary dribbling</strong> — unlike hanging. This is an important DD point.</p>', tags: ['More dramatic than hanging', 'No salivary dribbling'] },
  'str-pm-mark': { label: 'Strangulation — Mark on Neck', info: '<p><strong>Ligature strangulation mark:</strong> HORIZONTAL, COMPLETE, at or below thyroid cartilage. Pronounced vital reaction.</p><p><strong>Throttling marks:</strong> Curved abrasions (finger nails) + bruises in characteristic hand pattern — thumb on one side, 4 fingers on the other.</p><p><strong>Bansdola:</strong> Two parallel linear bruises.</p><p><strong>Vital reaction:</strong> PRONOUNCED — significant bruising, oedema, abrasions around the marks.</p><p><strong>Defence wounds:</strong> Often present on hands, forearms, face — signs of victim\\\'s struggle.</p>', tags: ['Vital reaction pronounced', 'Defence wounds suggest struggle'] },
  'str-pm-internal': { label: 'Strangulation — Internal Neck', info: '<p>Examined via bloodless neck-dissection. Findings are MORE marked than hanging:</p><ul><li><strong>Subcutaneous tissues</strong> — extensive haemorrhage + bruising</li><li><strong>Strap muscles</strong> — sternomastoid + omohyoid haemorrhage</li><li><strong>Hyoid bone</strong> — fracture more common (~30-40 %, esp. throttling)</li><li><strong>Cartilages</strong> — thyroid + cricoid fracture / bruising</li><li><strong>Trachea/larynx</strong> — congestion, oedema, mucosal abrasion</li><li><strong>Carotid sheath</strong> — bruising; rarely intimal tear</li></ul>', tags: ['More marked than hanging'] },
  'str-pm-asphyxial': { label: 'Strangulation — Asphyxial Signs (MARKED)', info: '<p>Classical asphyxial stigmata are typically <strong>more pronounced</strong> in strangulation than hanging, because death is slower → more time for petechiae to form.</p><ul><li><strong>Petechiae</strong> — numerous Tardieu spots on pleura, pericardium, conjunctivae</li><li><strong>Lungs</strong> — markedly congested, oedematous, sub-pleural petechiae</li><li><strong>Heart</strong> — right side distended with dark fluid blood</li><li><strong>Brain</strong> — severely congested + oedematous</li><li><strong>Visceral congestion</strong> — universal (liver, kidneys, spleen)</li></ul>', tags: ['More pronounced than hanging'] },

  'hyoid-anatomy': { label: 'Hyoid Bone — Anatomy', info: '<p>The <strong>hyoid bone</strong> is a U-shaped bone located at the level of <strong>C3 vertebra</strong>, suspended from the styloid process by stylohyoid ligament. It is the only bone in the body that does not articulate with another bone.</p><p><strong>Parts:</strong> 1 BODY (anterior) + 2 GREATER cornu (lateral, longer, postero-lateral) + 2 LESSER cornu (superior, shorter).</p><p><strong>Ossification:</strong> Greater cornu fuses with body in middle age (varies 25-45 years). Younger hyoid is more flexible → less fracture in young victims.</p><p><strong>Clinical pearl:</strong> Hyoid fracture in a victim under 25 years is unusual and should prompt suspicion of significant force.</p>', tags: ['U-shape', 'C3 level', 'Fusion in middle age'] },
  'hyoid-inout': { label: 'Inward Compression (IN-and-OUT)', info: '<p><strong>Direction:</strong> Both greater cornua pushed INWARD.</p><p><strong>Fracture site:</strong> Body or junction of body + greater cornu.</p><p><strong>Periosteum:</strong> Outer torn, inner intact.</p><p><strong>Seen in:</strong> THROTTLING — bilateral compression by hands on the neck pushes the cornua inward.</p><p><strong>Vital reaction:</strong> Haemorrhage in surrounding tissue confirms antemortem fracture.</p><p>Most common hyoid fracture pattern in throttling.</p>', tags: ['Throttling pattern', 'Outer periosteum torn'] },
  'hyoid-outin': { label: 'Outward Compression (OUT-and-IN)', info: '<p><strong>Direction:</strong> Cornua splay OUTWARD.</p><p><strong>Mechanism:</strong> Ligature pulls upward (as in hanging) → produces a splaying force on the cornua.</p><p><strong>Fracture site:</strong> Greater cornu tip.</p><p><strong>Periosteum:</strong> Outer intact, inner torn.</p><p><strong>Seen in:</strong> HANGING with high knot position.</p><p>Direction of periosteum tear differentiates hanging from throttling fractures.</p>', tags: ['Hanging pattern', 'Inner periosteum torn'] },
  'hyoid-ap': { label: 'Antero-Posterior Compression', info: '<p><strong>Direction:</strong> Cornua pushed BACKWARDS by direct anterior force.</p><p><strong>Mechanism:</strong> Direct anterior force on neck — palmar strangulation, blunt force trauma to neck, direct blow.</p><p><strong>Fracture site:</strong> Variable; can be body.</p><p><strong>Less common</strong> pattern; requires direct frontal force on the neck.</p>', tags: ['Direct anterior force'] },

  'suf-smothering': { label: 'Smothering', info: '<p>Closing of <strong>MOUTH + NOSE externally</strong>.</p><p><strong>Agents:</strong> Pillow, hand, plastic bag, cloth, soft tissue.</p><p><strong>PM findings:</strong> Bruises / abrasions around the mouth and nostrils. Plastic bag may leave imprint.</p><p><strong>Common scenarios:</strong></p><ul><li>Infants (overlying / SIDS differential)</li><li>Homicide of debilitated or sleeping person</li><li>Plastic bag suicide (terminally ill, depression)</li></ul>', tags: ['External obstruction', 'Pillow / plastic bag'] },
  'suf-gagging': { label: 'Gagging', info: '<p>Material forced <strong>INTO mouth</strong> to block the oral cavity and pharynx.</p><p><strong>Agents:</strong> Cloth, handkerchief, paper, tape across mouth.</p><p><strong>PM findings:</strong> Foreign material in oropharynx; abrasions on lips; teeth marks on cheek mucosa from biting on gag.</p><p><strong>Common in:</strong> Burglary victims (silenced + restrained); kidnapping.</p>', tags: ['Material into mouth', 'Restrained victims'] },
  'suf-choking': { label: 'Choking', info: '<p>INTERNAL obstruction of the airway by a foreign body.</p><p><strong>"Bolus death":</strong> Food bolus stuck at larynx → triggers vagal reflex → sudden cardiac arrest (mechanism: not pure asphyxia but vagal-mediated death).</p><p><strong>PM:</strong> Foreign body retrieved from larynx / trachea on autopsy.</p><p><strong>Common in:</strong> Elderly, drunk persons, dementia patients, neurological dysphagia.</p>', tags: ['Internal obstruction', 'Bolus death = vagal'] },
  'suf-traumatic': { label: 'Traumatic Asphyxia', info: '<p>External compression of the <strong>CHEST</strong> preventing respiratory movements.</p><p><strong>Causes:</strong> Crowd crush, stampede, building collapse, vehicle pinning, industrial accident.</p><p><strong>Cardinal sign:</strong> <strong>Masque ecchymotique</strong> — deep blue/purple discolouration of face, neck, upper chest above the level of compression. Caused by reflux of venous blood with no valves.</p><p>Pathognomonic finding when present.</p>', tags: ['Chest compression', 'Masque ecchymotique'] },
  'suf-overlying': { label: 'Overlying / SIDS DD', info: '<p><strong>Overlying:</strong> Adult accidentally smothers an infant while co-sleeping. Mostly accidental, especially in overcrowded households.</p><p><strong>SIDS</strong> (Sudden Infant Death Syndrome): Sudden unexplained death of infant &lt; 1 year — the differential for overlying.</p><p><strong>Distinguishing:</strong> requires detailed scene reconstruction + autopsy + exclusion. SIDS = diagnosis of exclusion.</p><p>Detailed in Ch 20 (Infant Deaths and Female Feticide).</p>', tags: ['Cross-ref Ch 20', 'Co-sleeping risk'] },
  'suf-burking': { label: 'Burking', info: '<p>Combined <strong>smothering + chest compression</strong> — sitting on the chest while closing the mouth and nose.</p><p><strong>Named after William Burke</strong> (1828 Edinburgh) who, with William Hare, murdered 16 people by this method and sold the bodies to anatomy schools.</p><p>Produces few external marks — historically used to make deaths look natural.</p>', tags: ['William Burke 1828'] },

  'drown-definition': { label: 'Drowning — Definition', info: '<p>Death by asphyxia caused by <strong>immersion of mouth and nose in a fluid medium</strong> — fluid fills the airways preventing gas exchange.</p><p>"Fluid" is not limited to water — can be sewage, mud, oil, blood, or any liquid that can occlude airways.</p><p><strong>Manner of death:</strong> mostly accidental; sometimes suicidal (especially in deep water); rarely homicidal (forcibly held under).</p>', tags: ['Immersion asphyxia', 'Mostly accidental'] },
  'drown-wet': { label: 'Wet Drowning (~90%)', info: '<p>The classic drowning — fluid is <strong>aspirated into the lungs</strong>.</p><p><strong>Fresh water</strong> (hypotonic, &lt; blood osmolality): water absorbed into circulation → haemodilution → haemolysis → hyperkalaemia → ventricular fibrillation → death in 5-10 min.</p><p><strong>Sea water</strong> (hypertonic, &gt; blood osmolality): pulls water OUT of circulation into alveoli → severe pulmonary oedema → hypovolaemia → hypoxia → death in 8-12 min.</p><p>Most common type — accounts for ~90 % of drowning deaths.</p>', tags: ['~90% of drownings', 'Fresh vs sea differs in mechanism'] },
  'drown-dry': { label: 'Dry Drowning (~10%)', info: '<p><strong>Mechanism:</strong> Sudden <strong>LARYNGOSPASM</strong> at first contact of water with the larynx → larynx clamps shut → asphyxia → death.</p><p><strong>Lungs:</strong> Remain DRY at autopsy — no fluid aspirated.</p><p><strong>Common in:</strong> Cold-water entry, panic, intoxication, drug overdose.</p><p><strong>Diagnosis:</strong> Difficult — by exclusion of other causes + history of immersion.</p><p>Distinguish from hydrocution (which is vagal cardiac arrest, not laryngospasm).</p>', tags: ['~10%', 'Laryngospasm', 'Lungs dry'] },
  'drown-secondary': { label: 'Secondary (Post-immersion) Drowning', info: '<p>Death HOURS to DAYS after rescue from drowning.</p><p><strong>Mechanism:</strong> Aspirated water damages pulmonary surfactant → delayed pulmonary oedema → ARDS or aspiration pneumonia → respiratory failure.</p><p><strong>Risk factors:</strong> Aspiration of large volume, cold water, prolonged immersion, fresh water (more haemolysis).</p><p><strong>Management:</strong> All rescued drowning victims should be observed for at least 24 hours — even if initially asymptomatic.</p>', tags: ['Hours-days after rescue', 'ARDS / pneumonia'] },
  'drown-immersion': { label: 'Immersion (Hydrocution) — Cold Shock', info: '<p>Sudden death on entering <strong>cold water</strong> — within seconds to 1-2 minutes.</p><p><strong>Mechanism:</strong> <strong>VAGAL INHIBITION</strong> — cold water on skin or hitting the epigastrium triggers a reflex cardiac arrest via vagal pathway.</p><p><strong>Lungs:</strong> May be DRY — death is too fast for water aspiration.</p><p><strong>Synonyms:</strong> "Hydrocution" · "Cold shock".</p><p><strong>Risk factors:</strong> Sudden plunge into cold water, full stomach, alcohol, cardiac disease.</p>', tags: ['Vagal inhibition', 'Cold water', 'Seconds-min'] },
  'drown-stages': { label: '5 Stages of (Wet) Drowning', info: '<p>The classical sequence in wet drowning:</p><ol><li><strong>Surprise</strong> (5-10 sec) — sudden immersion triggers reflex inspiration; water enters airways.</li><li><strong>Resistance / Struggle</strong> (1-2 min) — breath-holding, violent struggle, panic, attempts to rise. The visible "drowning person" phase.</li><li><strong>Deep respiration phase</strong> (1-2 min) — involuntary deep breaths from CO₂ accumulation → massive water inhalation. Patient becomes unconscious.</li><li><strong>Convulsions / Exhaustion</strong> (1 min) — generalised seizures from cerebral hypoxia.</li><li><strong>Death</strong> — total respiratory + cardiac arrest. Typical total duration: ~5 minutes.</li></ol>', tags: ['~5 min total', '5 stages'] },

  'drown-pm-external': { label: 'Drowning — External PM Findings', info: '<p><strong>Face:</strong> Pale (early) or cyanosed (late); puffy.</p><p><strong>Mouth/nostrils:</strong> <strong>Champignon mushroom froth</strong> — fine, white-pinkish, persistent foam. Pathognomonic when present.</p><p><strong>Eyes:</strong> Open; conjunctival haemorrhages.</p><p><strong>Cutis anserina</strong> (goose-skin): Erection of hair follicles from cold + rigor of arrectores pilorum muscles. Non-specific (also in cold deaths).</p><p><strong>Washerwoman\\\'s hand:</strong> Wrinkling + sodden whitening of palms and soles after &gt; 2 hours immersion.</p><p><strong>Clenched fists:</strong> Cadaveric spasm — may grasp weeds, mud, fabric — confirms antemortem struggle.</p>', tags: ['Champignon froth', 'Washerwoman hand', 'Cutis anserina'] },
  'drown-pm-lungs': { label: 'Drowning — Lung Findings (★)', info: '<p>Key autopsy findings on the lungs in wet drowning:</p><ul><li><strong>Emphysema aquosum:</strong> Lungs ballooned, heavy, overlap at the midline, pit on pressure.</li><li><strong>Paltauf haemorrhages:</strong> Sub-pleural bluish-red haemorrhages from rupture of alveolar capillaries. Relatively specific for drowning.</li><li><strong>Cut surface:</strong> Frothy fluid + blood-stained mucus exudes.</li><li><strong>Airways:</strong> Fine frothy fluid in trachea, bronchi.</li><li><strong>Stomach:</strong> Water + sand / silt (swallowed during struggle).</li><li><strong>Middle ear:</strong> Haemorrhage (Niles sign — differential: head injury).</li></ul>', tags: ['Emphysema aquosum', 'Paltauf haemorrhages'] },
  'drown-diatom': { label: 'Diatom Test — Gold Standard', info: '<p><strong>Principle:</strong> Diatoms are microscopic algae present in natural water bodies. In antemortem drowning, diatoms are aspirated into the lungs → enter circulation via pulmonary capillaries → reach distant organs (brain, kidney, bone marrow, sternum) via active circulation.</p><p><strong>Test procedure:</strong> Acid-digestion of organ samples (typically femur bone marrow — deep tissue, less external contamination). The sediment is examined under microscopy for characteristic diatom skeletons.</p><p><strong>Positive test:</strong> Presence of diatoms in distant organs ⟹ <strong>ANTEMORTEM drowning</strong> (circulation was active when water entered lungs).</p><p><strong>Limitations:</strong></p><ul><li>False positives — environmental contamination, ingested water</li><li>False negatives — drowning in clean water (chlorinated pools, distilled water)</li><li>Must compare with diatoms from the water source</li></ul>', tags: ['Gold standard', 'Femur marrow ideal'] },
  'drown-misc': { label: 'Other Drowning Tests', info: '<p><strong>Gettler test:</strong> Compare chloride concentration in blood from L vs R heart. Fresh water drowning → ↑ in L heart (water absorbed into circulation).</p><p><strong>Specific gravity test:</strong> Blood specific gravity decreased in fresh-water drowning (haemodilution).</p><p><strong>Strontium test:</strong> Strontium in blood = sea-water drowning marker.</p><p><strong>Hydrocution (immersion):</strong> Lungs may be DRY because sudden vagal arrest precedes aspiration. Diagnosis on history + cold water + sudden collapse.</p>', tags: ['Gettler · Specific gravity · Strontium'] }
`;

const MCQS_ADD = `,
  'VA-04': [
    { stem: 'The most reliable single feature distinguishing a hanging mark from a strangulation mark is:', options: ['Colour','Depth','Direction (oblique vs horizontal)','Width'], answerIdx: 2, explain: 'Direction — hanging is OBLIQUE (rises to knot); strangulation is HORIZONTAL.', tag: '[PG-Inspired]' },
    { stem: 'Parchmentisation of the ligature mark refers to:', options: ['Discolouration to yellow','Drying + shrinkage of compressed dermis → leathery dark mark','Lifting of skin','Petechial change'], answerIdx: 1, explain: 'Parchmentisation = drying + shrinkage of dermis beneath ligature → dark leathery appearance — key sign of vital reaction.', tag: '[UNIV]' }
  ],
  'VA-05': [
    { stem: 'Bansdola is a form of strangulation by:', options: ['Ligature','Hands','Wooden sticks','Bend of elbow'], answerIdx: 2, explain: '"Bans" = bamboo in Hindi. Bansdola = strangulation by two wooden sticks placed on either side of the neck.', tag: '[NEET-PG 2016]' },
    { stem: 'The strangulation method involving a ligature thrown from behind and tightened with a stick (windlass) is:', options: ['Throttling','Garroting','Mugging','Bansdola'], answerIdx: 1, explain: 'Garroting — Spanish judicial execution method using ligature + tightening stick.', tag: '[PG-Inspired]' },
    { stem: 'The MOST common site of hyoid bone fracture occurs in:', options: ['Hanging','Ligature strangulation','Throttling','Drowning'], answerIdx: 2, explain: 'Throttling — bilateral manual compression often fractures hyoid greater cornu (~30-40 %).', tag: '[PG-Inspired]' }
  ],
  'VA-06': [
    { stem: 'A dead body is brought for evaluation. On post-mortem examination, a ligature completely encircled the neck, horizontal, and below the thyroid level was seen. There was no dribbling of saliva. What is the cause of death?', options: ['Throttling','Ligature strangulation','Gagging','Hanging'], answerIdx: 1, explain: 'Horizontal + complete + below thyroid + no salivary dribbling → ligature strangulation (not hanging — hanging would be oblique, incomplete, above thyroid, with salivary dribbling).', tag: '[NEET-PG 2022]' },
    { stem: 'In strangulation, defence wounds are typically found on:', options: ['Back','Hands and forearms','Lower limbs','Head only'], answerIdx: 1, explain: 'Defence wounds on hands, forearms, face — sign of struggle by the victim trying to remove the ligature/hands.', tag: '[PG-Inspired]' }
  ],
  'VA-07': [
    { stem: 'In which of the following is hyoid bone fracture most common?', options: ['Suicidal hanging','Ligature strangulation','Throttling','Drowning'], answerIdx: 2, explain: 'Throttling has the highest hyoid fracture rate (~30-40 %). Hanging fractures hyoid in &lt;30 %; drowning rarely.', tag: '[PG-Inspired]' },
    { stem: 'In throttling, the typical hyoid fracture pattern is:', options: ['Outward compression (out-and-in)','Inward compression (in-and-out)','Antero-posterior','Vertical'], answerIdx: 1, explain: 'Throttling = bilateral inward compression by hands → in-and-out pattern · outer periosteum torn, inner intact.', tag: '[PG-Inspired]' }
  ],
  'VA-08': [
    { stem: 'Masque ecchymotique is the cardinal sign of:', options: ['Smothering','Gagging','Choking','Traumatic asphyxia'], answerIdx: 3, explain: 'Masque ecchymotique = deep blue discolouration of face/neck/upper chest from venous reflux during chest compression — pathognomonic for traumatic asphyxia.', tag: '[PG-Inspired]' },
    { stem: 'Bolus death refers to:', options: ['Choking from food bolus + vagal reflex causing cardiac arrest','Massive haemorrhage','Drowning in alcohol','Asphyxia from chest crush'], answerIdx: 0, explain: 'Bolus death = food bolus stuck at larynx triggers vagal reflex → sudden cardiac arrest. Mechanism is vagal, not pure asphyxia.', tag: '[UNIV]' }
  ],
  'VA-09': [
    { stem: 'Mechanism of death in DRY drowning is:', options: ['Massive water aspiration','Sudden laryngospasm with closure of larynx','Vagal cardiac arrest','Haemolysis'], answerIdx: 1, explain: 'Dry drowning (~10 %) = sudden laryngospasm at first water contact → larynx clamps shut → asphyxia. Lungs remain dry at autopsy.', tag: '[PG-Inspired]' },
    { stem: 'Hydrocution (immersion drowning) is caused by:', options: ['Aspiration of cold water','Vagal cardiac arrest from cold-water shock','Pulmonary embolism','Haemolysis'], answerIdx: 1, explain: 'Hydrocution = sudden vagal cardiac arrest on entering cold water (cold shock on skin / epigastrium). Death within seconds-minutes.', tag: '[QBank-Inspired]' },
    { stem: 'In fresh-water drowning, the mechanism of death is:', options: ['Pulmonary oedema from hypertonic water','Haemodilution → haemolysis → hyperkalaemia → VF','Cold shock','Air embolism'], answerIdx: 1, explain: 'Fresh water is hypotonic → absorbed into circulation → haemodilution → haemolysis → hyperkalaemia → VF. Sea water = opposite (pulmonary oedema).', tag: '[PG-Inspired]' }
  ],
  'VA-10': [
    { stem: 'The mushroom-like froth at the mouth and nostrils in a drowned body is called:', options: ['Cutis anserina','Champignon mushroom froth','Washerwoman\\\'s hand','Masque ecchymotique'], answerIdx: 1, explain: 'Champignon mushroom froth — fine white-pinkish persistent foam at mouth/nostrils; pathognomonic for antemortem drowning.', tag: '[PG-Inspired]' },
    { stem: 'In the diatom test, the BEST sample for examination is:', options: ['Lung tissue','Stomach contents','Femur bone marrow','Blood'], answerIdx: 2, explain: 'Femur bone marrow — deep tissue, minimal contamination. Diatoms reaching marrow confirm antemortem circulation = antemortem drowning.', tag: '[PG-Inspired]' },
    { stem: 'Washerwoman\\\'s hand in a drowned body indicates:', options: ['Antemortem drowning','Postmortem submersion','Immersion for &gt; 2 hours (non-specific)','Hydrocution'], answerIdx: 2, explain: 'Washerwoman\\\'s hand = wrinkling + sodden whitening of palms/soles. Develops after &gt; 2 hours in water. Indicates duration of immersion, NOT antemortem vs postmortem.', tag: '[UNIV]' },
    { stem: 'Paltauf haemorrhages are found on the:', options: ['Conjunctivae','Sub-pleural surface of lungs','Pericardium','Brain'], answerIdx: 1, explain: 'Paltauf haemorrhages = bluish-red sub-pleural haemorrhages from alveolar capillary rupture. Relatively specific for drowning.', tag: '[PG-Inspired]' }
  ]
`;

const DTS_ADD = `,
  {
    id: 'DT-3', title: 'Wet vs Dry vs Secondary vs Immersion (Hydrocution) Drowning', shortTitle: 'Drowning types',
    columns: ['Feature','Wet (~90%)','Dry (~10%)','Secondary','Immersion (hydrocution)'],
    rows: [
      ['Mechanism','Water aspirated into lungs','Laryngospasm — no aspiration','Delayed pulmonary oedema hrs-days after rescue','<strong>Vagal arrest</strong> from cold-water shock'],
      ['Time to death','5-10 min','Seconds-minutes','Hours-days','Seconds to 1-2 min'],
      ['Lungs at PM','Wet, emphysema aquosum, Paltauf','<strong>DRY</strong> (no fluid)','Pulmonary oedema, ARDS','May be DRY'],
      ['Diatom test','Usually +ve','Negative','+ve','Negative (no aspiration)'],
      ['Champignon froth','Usually present','Usually absent','Absent','Absent']
    ],
    parentDiagrams: ['VA-09','VA-10'],
    mcqs: [
      { stem: 'In dry drowning, the lungs are characteristically:', options: ['Heavy and wet','DRY (no aspiration due to laryngospasm)','Filled with blood','Collapsed'], answerIdx: 1, explain: 'Dry drowning — laryngospasm prevents water from reaching lungs → DRY at autopsy.', tag: '[PG-Inspired]' }
    ]
  },
  {
    id: 'DT-4', title: 'Throttling vs Ligature Strangulation', shortTitle: 'Throttling vs Ligature Strang.',
    columns: ['Feature','Throttling','Ligature Strangulation'],
    rows: [
      ['Agent','Hands','Ligature (rope, scarf, wire)'],
      ['Mark on neck','Curved abrasions + bruises (finger nail marks)','Single horizontal complete mark'],
      ['Hand pattern','Thumb on one side, 4 fingers on opposite','—'],
      ['Hyoid fracture rate','HIGHEST (~30-40%)','~20-30%'],
      ['Cartilage injury','Marked','Common'],
      ['Defence wounds','Often present','Often present'],
      ['Manner','Always HOMICIDAL','Mostly homicidal']
    ],
    parentDiagrams: ['VA-05','VA-06'],
    mcqs: [
      { stem: 'Which has the highest rate of hyoid bone fracture?', options: ['Hanging','Ligature strangulation','Throttling','Bansdola'], answerIdx: 2, explain: 'Throttling — manual compression often fractures hyoid (~30-40 %).', tag: '[PG-Inspired]' }
    ]
  }`;

const SUBJ_ADD = `,
  {
    id: 'SAQ-15.3', type: 'SAQ', marks: 5, time: '~12 min', tag: 'QBank',
    question: 'What are different hyoid bone fractures? Explain the different scenarios in which each type of fractures may be found.',
    answer: \`<h4>Hyoid bone anatomy</h4>
<p>U-shaped bone at C3 level. Parts: 1 body + 2 greater cornu (lateral) + 2 lesser cornu (superior). Younger hyoid is more flexible (greater cornu fuses with body in middle age) → less fracture in young victims.</p>
<h4>Three Patterns of Hyoid Fracture (by direction of compression)</h4>
<table><tr><th>Pattern</th><th>Direction</th><th>Periosteum</th><th>Scenario</th></tr>
<tr><td><strong>1. Inward compression (IN-and-OUT)</strong></td><td>Cornua pushed inward (toward midline)</td><td>Outer TORN; inner intact</td><td><strong>THROTTLING</strong> — bilateral manual compression. Most common pattern.</td></tr>
<tr><td><strong>2. Outward compression (OUT-and-IN)</strong></td><td>Cornua splay outward</td><td>Outer intact; inner TORN</td><td><strong>HANGING</strong> with high knot position. Ligature pulls upward → splaying force.</td></tr>
<tr><td><strong>3. Antero-posterior</strong></td><td>Cornua pushed backwards</td><td>Variable</td><td><strong>Palmar strangulation</strong> or direct blunt force trauma to anterior neck.</td></tr></table>
<h4>Frequency of hyoid fracture by cause of death</h4>
<ul><li><strong>Throttling</strong>: ~30-40 % (highest)</li>
<li><strong>Ligature strangulation</strong>: ~20-30 %</li>
<li><strong>Hanging</strong>: &lt; 30 %</li>
<li><strong>Drowning / smothering</strong>: rare</li>
<li><strong>Blunt trauma to neck</strong>: variable</li></ul>
<h4>Vital reaction</h4>
<p>To distinguish antemortem from postmortem fracture: presence of haemorrhage in surrounding soft tissues confirms antemortem origin. Postmortem fractures (e.g., from rough handling at autopsy) show no haemorrhage.</p>
<h4>Age factor</h4>
<p>Hyoid bone in young persons (&lt; 25 years) is flexible due to incomplete fusion of greater cornu with body — fracture is uncommon. In elderly (post-fusion), the bone is rigid and fractures more easily.</p>
<h4>Clinical relevance</h4>
<p>Hyoid fracture is suggestive of neck compression but is NOT diagnostic of mechanism by itself — the pattern (in-and-out vs out-and-in) helps differentiate throttling from hanging.</p>\`,
    sources: ['VA-07 (Hyoid Fractures)','DT-4 (Throttling vs Ligature)'],
    jumpToDiagram: 'VA-07'
  },
  {
    id: 'SAQ-15.4', type: 'SAQ', marks: 5, time: '~12 min', tag: 'QBank',
    question: 'Garroting — define, enumerate PM findings on Face and Neck.',
    answer: \`<h4>Definition</h4>
<p>Garroting (Garrote) is a form of <strong>ligature strangulation</strong> in which a ligature is thrown around the victim\\\'s neck <strong>from behind</strong> and tightened by a <strong>stick (windlass / tourniquet)</strong>. Originated as a Spanish judicial execution method.</p>
<h4>Manner of death</h4>
<p>Always <strong>HOMICIDAL</strong> — a sneak attack from behind, often with a co-perpetrator.</p>
<h4>PM Findings on Face</h4>
<ul><li><strong>Face</strong>: markedly congested + cyanosed (asphyxial)</li>
<li><strong>Eyes</strong>: bulging; pupils dilated; numerous conjunctival petechiae (Tardieu spots)</li>
<li><strong>Tongue</strong>: protruded, swollen, bitten</li>
<li><strong>Lips/ears</strong>: cyanosed; petechiae behind ears</li>
<li><strong>Bleeding</strong>: may be from nose/mouth in severe cases</li>
<li><strong>No salivary dribbling</strong> (unlike hanging)</li></ul>
<h4>PM Findings on Neck</h4>
<p><strong>External:</strong></p>
<ul><li><strong>Single horizontal complete ligature mark</strong>, often at or below thyroid level</li>
<li>Vital reaction — bruising, oedema, abrasions around the mark</li>
<li><strong>Stick / windlass impression</strong> — pressure mark at site where the stick was applied</li>
<li>Defence wounds on hands, forearms, face (struggle)</li></ul>
<p><strong>Internal (on neck dissection):</strong></p>
<ul><li>Extensive subcutaneous haemorrhage</li>
<li>Sternomastoid + strap muscle haemorrhage</li>
<li>Hyoid bone fracture in ~20-30 %</li>
<li>Thyroid + cricoid cartilage bruising / fracture</li>
<li>Tracheal / laryngeal congestion + mucosal abrasion</li>
<li>Carotid sheath bruising</li></ul>
<h4>General asphyxial signs (often pronounced)</h4>
<ul><li>Pleural + pericardial Tardieu spots</li>
<li>Pulmonary congestion + oedema</li>
<li>Right heart distention with dark fluid blood</li>
<li>Cerebral congestion</li>
<li>Visceral congestion</li></ul>
<h4>Medico-legal importance</h4>
<p>Garroting always homicidal — the windlass impression + sneak-attack scene strongly support homicide. Compare with self-strangulation (rare and usually with simple knot, never windlass).</p>\`,
    sources: ['VA-05 (Strangulation Types)','VA-06 (PM Strangulation)'],
    jumpToDiagram: 'VA-05'
  },
  {
    id: 'SAQ-15.5', type: 'SAQ', marks: 5, time: '~12 min', tag: 'QBank',
    question: 'Drowning — enumerate types, postmortem findings, medicolegal importance.',
    answer: \`<h4>Definition</h4>
<p>Death by asphyxia caused by immersion of mouth and nose in a fluid medium that fills the airways and prevents gas exchange.</p>
<h4>Four Types of Drowning</h4>
<ol><li><strong>Wet drowning (~90 %)</strong> — water aspirated into lungs. Fresh water → haemodilution → haemolysis → hyperkalaemia → VF (5-10 min). Sea water → pulmonary oedema → hypovolaemia → hypoxia (8-12 min).</li>
<li><strong>Dry drowning (~10 %)</strong> — sudden laryngospasm prevents aspiration. Lungs DRY at autopsy.</li>
<li><strong>Secondary drowning</strong> — death hours-days after rescue from ARDS / pneumonia due to surfactant damage.</li>
<li><strong>Immersion (hydrocution)</strong> — sudden vagal cardiac arrest on entering cold water. Lungs may be DRY. Death in seconds-minutes.</li></ol>
<h4>External Post-mortem Findings</h4>
<ul><li><strong>Champignon mushroom froth</strong> at mouth/nostrils (fine, white-pink, persistent) — pathognomonic for antemortem drowning</li>
<li><strong>Cutis anserina</strong> (goose-skin) — non-specific</li>
<li><strong>Washerwoman\\\'s hand</strong> — wrinkling of palms/soles after &gt; 2 hours immersion (duration only, not antemortem proof)</li>
<li><strong>Cadaveric spasm</strong> — clenched fists grasping weeds/mud — strong antemortem sign</li>
<li>Face pale (early) or cyanosed (late)</li>
<li>Conjunctival haemorrhages</li></ul>
<h4>Internal Post-mortem Findings</h4>
<ul><li><strong>Lungs</strong>: emphysema aquosum (heavy, ballooned, pit on pressure); <strong>Paltauf haemorrhages</strong> (sub-pleural bluish-red — relatively specific); frothy fluid on cut surface</li>
<li><strong>Airways</strong>: fine frothy fluid in trachea + bronchi</li>
<li><strong>Stomach</strong>: water + sand / silt (swallowed during struggle)</li>
<li><strong>Middle ear haemorrhage</strong> (Niles sign — DD with head injury)</li>
<li>Right heart distended with dark fluid blood</li>
<li>Visceral congestion</li></ul>
<h4>Key Tests</h4>
<ul><li><strong>Diatom test (gold standard)</strong>: acid-digestion of organs (especially femur marrow) → diatoms in distant organs = antemortem drowning</li>
<li><strong>Gettler test</strong>: chloride difference between L and R heart blood (fresh water → ↑ L heart)</li>
<li><strong>Specific gravity test</strong>: ↓ in fresh-water drowning (haemodilution)</li>
<li><strong>Strontium test</strong>: marker for sea-water drowning</li></ul>
<h4>Medicolegal Importance</h4>
<ul><li><strong>Manner of death</strong>: most accidental; some suicidal (deep water, weighted); rarely homicidal (forcibly held under)</li>
<li><strong>Differentiate antemortem vs postmortem submersion</strong> — diatom test, washerwoman\\\'s hand, vital reactions, cadaveric spasm</li>
<li><strong>Identify the body</strong> — bodies in water often decompose rapidly (aerial drowning, adipocere formation)</li>
<li><strong>Time of immersion</strong> — washerwoman\\\'s hand (2+ hrs), maceration of fingernails (24-48 hrs), skin slippage (3-5 days), adipocere (weeks-months)</li>
<li><strong>Cause and manner</strong> — depend on combining external/internal findings with scene investigation</li></ul>\`,
    sources: ['VA-09 (Drowning Types)','VA-10 (PM Drowning)','DT-3 (Drowning types)'],
    jumpToDiagram: 'VA-09'
  }`;

// === DO THE SURGERY ===

// 1. Replace SVG placeholders
for (const [key, svg] of Object.entries(SVGS)) {
  const regex = new RegExp("const SVG_" + key + " = `<svg viewBox=\"0 0 1600 600\"[\\s\\S]*?</svg>`;", 'g');
  if (!regex.test(data)) { console.error('No match for SVG_' + key); continue; }
  data = data.replace(regex, "const SVG_" + key + " = `" + svg + "`;");
  console.log('  ✓ replaced SVG_' + key);
}

// 2. Append NODES (insert before final closing brace of NODES)
data = data.replace(/(\bconst NODES = \{)([\s\S]*?)(\n\};)/, '$1$2' + NODES_ADD + '$3');

// 3. Append MCQs to existing empty arrays
data = data.replace(/'VA-04': \[\],\s*'VA-05': \[\],\s*'VA-06': \[\],\s*'VA-07': \[\],\s*'VA-08': \[\],\s*'VA-09': \[\],\s*'VA-10': \[\]/, MCQS_ADD.replace(/^,\s*/, ''));

// 4. Append DTs (before closing ];)
data = data.replace(/(const DIFF_TABLES = \[)([\s\S]*?)(\n\];)/, '$1$2' + DTS_ADD + '$3');

// 5. Append Subjective Qs
data = data.replace(/(const SUBJ = \[)([\s\S]*?)(\n\];)/, '$1$2' + SUBJ_ADD + '$3');

// 6. Update diagram-list entries to wire nodes + mcqs
const diagramReplacements = {
  'VA-04': `{ id: 'VA-04', title: 'Ligature Mark Features (7)', shortTitle: 'Ligature Mark — 7 Features', svg: SVG_VA04,
      prereqs: [{term:'Vital reaction',meaning:'Tissue response (haemorrhage / oedema) to injury — proves antemortem origin.'},{term:'Parchmentisation',meaning:'Drying + shrinkage of compressed dermis → dark leathery mark.'},{term:'Knot impression',meaning:'Pressure mark at site of ligature knot on the skin.'}],
      nodes: nodeList(['lm-direction','lm-continuity','lm-level','lm-texture','lm-colour','lm-knot','lm-vital']),
      mcqs: MCQS['VA-04']
    }`,
  'VA-05': `{ id: 'VA-05', title: 'Strangulation — 6 Subtypes', shortTitle: 'Strangulation Types', svg: SVG_VA05,
      prereqs: [{term:'Ligature strangulation',meaning:'Strangulation by rope, scarf, etc.'},{term:'Throttling',meaning:'Manual strangulation by hands.'},{term:'Bansdola',meaning:'Strangulation by two wooden sticks.'},{term:'Garroting',meaning:'Ligature + tightening stick from behind.'},{term:'Mugging',meaning:'Chokehold by bend of elbow.'},{term:'Palmar strangulation',meaning:'Heel of palm pressed on anterior neck.'}],
      nodes: nodeList(['str-ligature','str-throttling','str-bansdola','str-garroting','str-mugging','str-palmar']),
      mcqs: MCQS['VA-05']
    }`,
  'VA-06': `{ id: 'VA-06', title: 'PM Findings in Strangulation', shortTitle: 'PM Strangulation', svg: SVG_VA06,
      prereqs: [{term:'Defence wounds',meaning:'Injuries on hands/forearms from victim trying to ward off attack.'},{term:'Asphyxial stigmata',meaning:'Classical post-mortem signs of asphyxia.'}],
      nodes: nodeList(['str-pm-face','str-pm-mark','str-pm-internal','str-pm-asphyxial']),
      mcqs: MCQS['VA-06']
    }`,
  'VA-07': `{ id: 'VA-07', title: 'Hyoid Bone Fractures — 3 Patterns', shortTitle: 'Hyoid Fractures', svg: SVG_VA07,
      prereqs: [{term:'Greater cornu',meaning:'Lateral, longer part of hyoid bone — most common fracture site.'},{term:'In-and-out fracture',meaning:'Inward compression pattern (throttling).'},{term:'Out-and-in fracture',meaning:'Outward splaying pattern (hanging).'},{term:'Periosteum',meaning:'Outer fibrous covering of bone — its tear direction differentiates fracture pattern.'}],
      nodes: nodeList(['hyoid-anatomy','hyoid-inout','hyoid-outin','hyoid-ap']),
      mcqs: MCQS['VA-07']
    }`,
  'VA-08': `{ id: 'VA-08', title: 'Suffocation Group — 6 Mechanisms', shortTitle: 'Suffocation', svg: SVG_VA08,
      prereqs: [{term:'Smothering',meaning:'External obstruction of mouth + nose.'},{term:'Gagging',meaning:'Material forced into mouth blocking pharynx.'},{term:'Choking',meaning:'Internal airway obstruction by foreign body.'},{term:'Traumatic asphyxia',meaning:'External chest compression preventing respiration.'},{term:'Masque ecchymotique',meaning:'Blue discolouration of face/neck/upper chest in traumatic asphyxia.'},{term:'Bolus death',meaning:'Vagal cardiac arrest from food bolus stuck at larynx.'}],
      nodes: nodeList(['suf-smothering','suf-gagging','suf-choking','suf-traumatic','suf-overlying','suf-burking']),
      mcqs: MCQS['VA-08']
    }`,
  'VA-09': `{ id: 'VA-09', title: 'Drowning — 4 Types &amp; 5 Stages', shortTitle: 'Drowning Types', svg: SVG_VA09,
      prereqs: [{term:'Wet drowning',meaning:'Water aspirated into lungs — ~90% of cases.'},{term:'Dry drowning',meaning:'Laryngospasm prevents aspiration — lungs remain dry.'},{term:'Hydrocution',meaning:'Sudden vagal cardiac arrest on cold water entry.'},{term:'Secondary drowning',meaning:'Death hours-days post rescue from ARDS/pneumonia.'},{term:'Haemodilution',meaning:'Decrease in blood concentration from absorbed water.'}],
      nodes: nodeList(['drown-definition','drown-wet','drown-dry','drown-secondary','drown-immersion','drown-stages']),
      mcqs: MCQS['VA-09']
    }`,
  'VA-10': `{ id: 'VA-10', title: 'PM Findings in Drowning + Diatom Test', shortTitle: 'PM Drowning', svg: SVG_VA10,
      prereqs: [{term:'Champignon mushroom froth',meaning:'Fine white-pink persistent foam at mouth/nostrils — pathognomonic.'},{term:'Cutis anserina',meaning:'Goose-skin from erection of hair follicles.'},{term:'Washerwoman\\\'s hand',meaning:'Wrinkling of palms/soles after &gt;2 hrs immersion.'},{term:'Emphysema aquosum',meaning:'Ballooned heavy lungs in drowning.'},{term:'Paltauf haemorrhages',meaning:'Sub-pleural bluish-red haemorrhages in drowning.'},{term:'Diatom test',meaning:'Gold-standard test for antemortem drowning via microscopic algae.'}],
      nodes: nodeList(['drown-pm-external','drown-pm-lungs','drown-diatom','drown-misc']),
      mcqs: MCQS['VA-10']
    }`
};
for (const [id, replacement] of Object.entries(diagramReplacements)) {
  const regex = new RegExp("\\{ id: '" + id + "',[^}]*?mcqs: \\[\\] \\}", 'g');
  if (!regex.test(data)) { console.error('No match for', id); continue; }
  data = data.replace(regex, replacement);
  console.log('  ✓ wired diagram:', id);
}

fs.writeFileSync(DATA, data);
console.log('\\n✅ Ch 15 surgery complete.');
